credentials:
  usernames:
    beatit:
      email: richmondkantam@gmail.com
      logged_in: False # Will be managed automatically
      name: Richmond Kantam Nana Addo Yendam
      password: 'abc123' # Will be hashed automatically
cookie:
  expiry_days: 30
  key: cookie_signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
  - richmond.kantam@azubiafrica.org
users: